# -*- coding: utf-8 -*-
"""
Created on 2022-04-18 22:27:04
---------
@summary:
---------
@author: lirui
"""

from feapder import Item
import farmhash, re, datetime, os
from urllib import parse
from feapder.utils.tools import download_file
from feapder import setting
from feapder.utils.log import log


class ShexchangeItem(Item):
    """
    This class was generated by feapder
    command: feapder create -i shexchange
    """

    __table_name__ = "shexchange"
    __unique_key__ = ["url_object_id", "url"]

    def __init__(self, *args, **kwargs):
        # self.id = None
        self.created_at = None
        self.description = None
        self.url = None
        self.urlhash = None
        self.title = None
        self.file_s_name = None
        self.time = None
        self.downloaded = None

    def check_data(self, data):
        if data['CURL'] and data['CTITLE_TXT']:
            return True
        else:
            return False

    def load_item(self, data, base_url):
        if self.check_data(data) is True:
            if '山东高速' in data.get('CTITLE_TXT'):
                print(data)
            self.created_at = data.get('CRELEASETIME') + ' ' + data.get('CRELEASETIME2')
            self.description = data.get('CONTENT')
            self.url = parse.urljoin(base_url, data.get('CURL'))
            self.urlhash = farmhash.hash64(self.url)
            self.title = data.get('CTITLE_TXT')

            match = re.findall(r'/.*/(.*?\.pdf$|.*?\.doc$|.*?\.docx$|.*?\.htm$|.*?\.html$)', data.get('CURL'),re.I)
            if match:
                self.file_s_name = match[0]
            else:
                raise Exception(f"文件名匹配出错:{data.get('CURL')}")
            self.time = datetime.datetime.now()
            self.downloaded = 0
            return self
        else:
            raise ValueError(f"data有空值：{data}")

    def download_file(self, data, base_url):
        download_url = parse.urljoin(base_url, data.get('CURL'))
        file_path = os.path.join(setting.SH_DOWNLOAD_PATH, data.get('CTITLE_TXT') + self.file_s_name)

        log.info(f"此时的download_url:{download_url}")
        log.info(f"此时的file_path:{file_path}")

        if self.downloaded == 0:
            is_downloaded = download_file(download_url, file_path)
            if is_downloaded == 1:
                log.info(f"该文件下载成功:{data.get('CURL')}")
                self.downloaded = 1
            else:
                log.info(f"该文件下载有问题:{data.get('CURL')}")
        else:
            log.info(f"该文件已经下载:{data.get('CURL')}")

