# -*- coding: utf-8 -*-
"""
Created on 2022-04-19 21:44:38
---------
@summary:
---------
@author: lirui
"""

from feapder import Item, UpdateItem
import time, farmhash, re, datetime, os
from urllib import parse
from feapder import setting
from feapder.utils.tools import download_file
from feapder.utils.log import log


class SzexchangeItem(UpdateItem):
    """
    This class was generated by feapder
    command: feapder create -i szexchange
    """

    __table_name__ = "szexchange"
    __update_key__ = ["downloaded"]

    def __init__(self, *args, **kwargs):
        # self.id = None
        self.created_at = None
        self.description = None
        self.url = None
        self.urlhash = None
        self.title = None
        self.pdf_name = None
        self.jsonurl = None
        self.time = None
        self.downloaded = None

    def check_data(self, data):
        if data['docpuburl'] and data['doctitle']:
            return True
        else:
            return False

    def load_item(self, data, base_url):
        if self.check_data(data) is True:
            timeArray = time.localtime(data['docpubtime'] / 1000)
            otherStyleTime = time.strftime("%Y-%m-%d %H:%M:%S", timeArray)
            self.created_at = otherStyleTime
            self.description = data.get('doccontent')
            self.url = data.get('docpuburl')
            self.urlhash = farmhash.hash64(self.url)

            pattern = re.compile(r'<[^>]+>', re.S)
            title = pattern.sub('', data.get('doctitle'))
            self.title = title

            match = re.findall(r'/.*/(.*?.pdf)', data.get('docpuburl'), re.I)
            if match:
                self.pdf_name = match[0]
            else:
                self.jsonurl = parse.urljoin(base_url, data['docpubjsonurl'])
            self.time = datetime.datetime.now()
            return self

        else:
            raise ValueError(f"data有空值：{data}")

    def download_file(self, data):
        download_url = data.get('docpuburl')
        if self.pdf_name:
            file_path = os.path.join(setting.SZ_DOWNLOAD_PATH, self.title + self.pdf_name)

            log.info(f"此时的download_url:{download_url}")
            log.info(f"此时的file_path:{file_path}")

            if self.downloaded == 0:
                is_downloaded = download_file(download_url, file_path)
                if is_downloaded == 1:
                    log.info(f"该文件下载成功:{data.get('docpuburl')}")
                    self.downloaded = 1
                else:
                    log.info(f"该文件下载有问题:{data.get('docpuburl')}")
            else:
                log.info(f"该文件已经下载:{data.get('docpuburl')}")
        else:
            log.info(f"该链接:{data.get('docpuburl')}是jsonurl，没有pdf文件")


if __name__ == "__main__":
    print(os.path.join(os.path.dirname(os.getcwd()), 'download', 'sz'))

